### PR TITLE
feat: eth default token list

### PR DESCRIPTION
**Pull request by Chef-Yogi**
TODO: update the token icon from the design team

### CODE REVIEW

**Comment by chef-jojo** [comment]
Please fix the tests. Need to add multicall support for chain id 1

**Comment by Chef-Yogi** [comment]
@chef-jojo fixed

**Review by chef-jojo — APPROVED** [review]
FYI, next time can use `@pancakeswap/multicall`

**Comment by Chef-Yogi** [comment]
got it

**Pull request merged**
